/** Bing Webmaster Tools integration barrel. */

export {
  BING_BASE_URL,
  BING_REQUIRED_ENV,
  BING_SOURCE,
  BING_SITE_PAGE_KEY,
  BING_PAGE_ROW_QUERY,
  BING_DATA_LAG_DAYS,
  BING_DEFAULT_WINDOW_DAYS,
  BING_MAX_HISTORY_DAYS,
  isBingConfigured,
  parseBingDate,
  decodeCrawlIssues,
  getUserSites,
  getRankAndTrafficStats,
  getQueryStats,
  getPageStats,
  getUrlTrafficInfo,
  getCrawlStats,
  getCrawlIssues,
  getLinkCounts,
  getUrlLinks,
  submitUrl,
  submitUrlBatch,
  submitFeed,
  getFeeds,
  readBingConfig,
  ensureBingIntegration,
  listBingSites,
  submitBingUrls,
  submitBingSitemap,
  getBingCrawlIssues,
  bingIntegrationHealth,
  syncBing,
} from './webmaster';

export type {
  BingUnsupported,
  BingEndpointResult,
  BingSite,
  BingTrafficStat,
  BingQueryStat,
  BingPageStat,
  BingUrlTrafficInfo,
  BingCrawlStat,
  BingCrawlIssue,
  BingLinkCount,
  BingInboundLink,
  BingFeed,
  BingIntegrationConfig,
  EnsureBingIntegrationResult,
  SubmitBingUrlsResult,
  SyncBingInput,
} from './webmaster';
